apiVersion: v1
kind: ServiceAccount
metadata:
  name: codestream
  namespace: tomcat
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: codestream
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: codestream
    namespace: tomcat
# Need to figure out how to create repeatable token
# For now using admin user token